---
- set_fact:
    vmware_provider_ids: []

- name: CFME | Add Control Profile to VMware Providers | Get the profile ID
  uri:
    url: https://localhost/api/policy_profiles?filter[]=name=VM+SmartState+Analysis+profile
    method: GET
    user: admin
    password: "{{ default_admin_password }}"
    force_basic_auth: yes
    validate_certs: no
    body_format: json
  register: rest_return
  
- set_fact:
    control_profile_href: "{{ rest_return.json.resources[0].href }}"
    
- debug:
    var: control_profile_href
    
- name: CFME | Add Control Profile to VMware Providers | Get the VMware provider IDs
  uri:
    url: https://localhost/api/providers?filter[]=type=ManageIQ::Providers::Vmware::InfraManager&expand=resources&attributes=name,id
    method: GET
    user: admin
    password: "{{ default_admin_password }}"
    force_basic_auth: yes
    validate_certs: no
    body_format: json
  register: rest_return
    
- set_fact:
    vmware_provider_ids: "{{ vmware_provider_ids + [ item ] }}"
  with_items: "{{ rest_return|json_query('json.resources[*].id') }}"
    
- debug:
    var: vmware_provider_ids  

- name: CFME | Add Control Profile to VMware Providers | Assign the profile the VMware provider IDs
  uri:
    url: https://localhost/api/providers/{{ item }}/policy_profiles
    method: POST
    user: admin
    password: "{{ default_admin_password }}"
    force_basic_auth: yes
    validate_certs: no
    body_format: json
    body:
      action: assign
      resource:
        href: "{{ control_profile_href }}"
  with_items: "{{ vmware_provider_ids }}"
  register: rest_return
  
- debug:
    var: rest_return 

